// 主项目(控件库)公共出口。
// 非公共件清单(FINAL 评审 I-2:刻意不导出,与遗漏区分):demo/内部演示件
// ThemeShadowDemo.vue、RatingRecipe.vue,以及 richtext/ 目录 8 子件
// (RichTextBlock 的内部解析/渲染件,经 RichTextBlock.vue 间接使用)。
export * as standardUiCommands from './utils/standardUiCommands'
export * as uiCommand from './utils/uiCommand'
export * as themeShadow from './utils/themeShadow'
export * as transitions from './utils/transitions'
export * as easingFunctions from './utils/easingFunctions'
export * as SystemBackdropElement from './components/SystemBackdropElement.vue'
// 所有对外暴露的控件与工具统一在此导出,供 demo 示例站与外部使用者引用。
export { default as SplitView } from './components/SplitView.vue'
export { default as SwipeControl } from './components/SwipeControl.vue'
export { default as SwipeItem } from './components/SwipeItem.vue'
export * from './utils/geometry'
export { default as BitmapIcon } from './components/BitmapIcon.vue'
export { default as ParallaxView } from './components/ParallaxView.vue'
export { default as AnimatedIcon } from './components/AnimatedIcon.vue'
export { default as AcrylicBrush } from './components/AcrylicBrush.vue'
export { default as NavigationView } from './components/NavigationView.vue'
export { default as MenuBarItem } from './components/MenuBarItem.vue'
export { default as MenuBar } from './components/MenuBar.vue'
export { default as AppBarSeparator } from './components/AppBarSeparator.vue'
export { default as AppBarButton } from './components/AppBarButton.vue'
export { default as ItemContainer } from './components/ItemContainer.vue'
export { default as ItemsView } from './components/ItemsView.vue'
export { default as GridViewItem } from './components/GridViewItem.vue'
export { default as GridView } from './components/GridView.vue'
export { default as Border } from './components/Border.vue'
export { default as AutoSuggestBox } from './components/AutoSuggestBox.vue'
export { default as Button } from './components/Button.vue'
export { default as BreadcrumbBar } from './components/BreadcrumbBar.vue'
export { default as CalendarDatePicker } from './components/CalendarDatePicker.vue'
export { default as CalendarView } from './components/CalendarView.vue'
export { default as Canvas } from './components/Canvas.vue'
export { default as CheckBox } from './components/CheckBox.vue'
export { default as ColorPicker } from './components/ColorPicker.vue'
export { default as ComboBox } from './components/ComboBox.vue'
export { default as CommandBar } from './components/CommandBar.vue'
export { default as ContentDialog } from './components/ContentDialog.vue'
export { default as DatePicker } from './components/DatePicker.vue'
export { default as DropDownButton } from './components/DropDownButton.vue'
export { default as Ellipse } from './components/Ellipse.vue'
export { default as Expander } from './components/Expander.vue'
export { default as Flyout } from './components/Flyout.vue'
export { default as FlipView } from './components/FlipView.vue'
export { default as InfoBadge } from './components/InfoBadge.vue'
export { default as InfoBar } from './components/InfoBar.vue'
export { default as ScrollViewer } from './components/ScrollViewer.vue'
export { default as FontIcon } from './components/FontIcon.vue'
export { default as Grid } from './components/Grid.vue'
export { default as HyperlinkButton } from './components/HyperlinkButton.vue'
export { default as Line } from './components/Line.vue'
export { default as ListBox } from './components/ListBox.vue'
export { default as ListView } from './components/ListView.vue'
export { default as ListViewItem } from './components/ListViewItem.vue'
export { default as MenuFlyout } from './components/MenuFlyout.vue'
export { default as MenuFlyoutItem } from './components/MenuFlyoutItem.vue'
export { default as MenuFlyoutSeparator } from './components/MenuFlyoutSeparator.vue'
export { default as MenuFlyoutSubItem } from './components/MenuFlyoutSubItem.vue'
export { default as NumberBox } from './components/NumberBox.vue'
export { default as PasswordBox } from './components/PasswordBox.vue'
export { default as PersonPicture } from './components/PersonPicture.vue'
export { default as PipsPager } from './components/PipsPager.vue'
export { default as Pivot } from './components/Pivot.vue'
export { default as PivotItem } from './components/PivotItem.vue'
export { default as Path } from './components/Path.vue'
export { default as PathIcon } from './components/PathIcon.vue'
export { default as Polygon } from './components/Polygon.vue'
export { default as Polyline } from './components/Polyline.vue'
export { default as Popup } from './components/Popup.vue'
export { default as ProgressRing } from './components/ProgressRing.vue'
export { default as ProgressBar } from './components/ProgressBar.vue'
export { default as RadioButton } from './components/RadioButton.vue'
export { default as RadialGradientBrush } from './components/RadialGradientBrush.vue'
export { default as RatingControl } from './components/RatingControl.vue'
export { default as Rectangle } from './components/Rectangle.vue'
export { default as RelativePanel } from './components/RelativePanel.vue'
export { default as RepeatButton } from './components/RepeatButton.vue'
export { default as RefreshContainer } from './components/RefreshContainer.vue'
export { default as RefreshVisualizer } from './components/RefreshVisualizer.vue'
export { default as RichTextBlock } from './components/RichTextBlock.vue'
export { default as ScrollView } from './components/ScrollView.vue'
export { default as SelectorBar } from './components/SelectorBar.vue'
export { default as SelectorBarItem } from './components/SelectorBarItem.vue'
export { default as SplitButton } from './components/SplitButton.vue'
export { default as Slider } from './components/Slider.vue'
export { default as StackPanel } from './components/StackPanel.vue'
export { default as SymbolIcon } from './components/SymbolIcon.vue'
export { default as EntranceNavigationThemeTransition } from './components/EntranceNavigationThemeTransition.vue'
export { default as NavigationThemeTransition } from './components/NavigationThemeTransition.vue'
export { default as ImplicitTransitions } from './components/ImplicitTransitions.vue'
export { default as SystemBackdrop } from './components/SystemBackdrop.vue'
export { default as TextBox } from './components/TextBox.vue'
export { default as TextBlock } from './components/TextBlock.vue'
export { default as TabView } from './components/TabView.vue'
export { default as TabViewItem } from './components/TabViewItem.vue'
export { default as TimePicker } from './components/TimePicker.vue'
export { default as ToolTip } from './components/ToolTip.vue'
export { default as ToolTipService } from './components/ToolTipService.vue'
export { default as TreeView } from './components/TreeView.vue'
export { default as ToggleButton } from './components/ToggleButton.vue'
export { default as ToggleSplitButton } from './components/ToggleSplitButton.vue'
export { default as ToggleMenuFlyoutItem } from './components/ToggleMenuFlyoutItem.vue'
export { default as ToggleSwitch } from './components/ToggleSwitch.vue'
export { default as TeachingTip } from './components/TeachingTip.vue'
export { default as Viewbox } from './components/Viewbox.vue'

// —— FINAL 评审 I-2 出口缺口补齐(控件 7)——
export { default as AnimatedVisualPlayer } from './components/AnimatedVisualPlayer.vue'
export { default as AppBarToggleButton } from './components/AppBarToggleButton.vue'
export { default as ItemsRepeater } from './components/ItemsRepeater.vue'
export { default as RichEditBox } from './components/RichEditBox.vue'
export { default as TitleBar } from './components/TitleBar.vue'
export { default as WebView2 } from './components/WebView2.vue'
// TreeViewItem:源中为 TreeView 行部件,一并导出供自定义树结构组合(FINAL I-2)。
export { default as TreeViewItem } from './components/TreeViewItem.vue'

// —— utils 7(沿用 export * as 命名空间风格)——
export * as collectionLayouts from './utils/collectionLayouts'
export * as colorConvert from './utils/colorConvert'
export * as elementSound from './utils/elementSound'
export * as geometryBounds from './utils/geometryBounds'
export * as popup from './utils/popup'
export * as shapeGeometry from './utils/shapeGeometry'
export * as symbolIcons from './utils/symbolIcons'

// —— composables 2(Vue 惯例:函数直接平铺,import { useSelection } 可用)——
export * from './composables/usePopup'
export * from './composables/useReducedMotion'
export * from './composables/useSelection'
export * from './composables/useReveal'

// —— components/*.ts 助手 2(命名空间风格,避免平铺污染顶层名)——
export * as animatedIconSource from './components/AnimatedIconSource'
export * as radioButtonGroups from './components/radioButtonGroups'
